# Generated by Django 3.0.7 on 2020-06-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vital', models.CharField(max_length=10)),
                ('Observed_Value', models.FloatField()),
                ('Reference_Range_Lower_Range', models.FloatField()),
                ('Reference_Range_Upper_Range', models.FloatField()),
            ],
        ),
    ]
