# Generated by Django 3.0.7 on 2020-06-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20200621_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital_elems',
            name='phosphorous',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
