# Generated by Django 3.0.7 on 2020-06-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('Observed_Value', models.FloatField()),
                ('Reference_Range_Lower_Range', models.FloatField()),
                ('Reference_Range_Upper_Range', models.FloatField()),
            ],
        ),
    ]
