# Generated by Django 3.0.7 on 2020-06-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_auto_20200621_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vital_elems',
            name='cust_id',
        ),
    ]
