# Generated by Django 3.0.7 on 2020-06-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_remove_vital_elems_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital_elems',
            name='cust_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='health.General_detail'),
            preserve_default=False,
        ),
    ]
